/**
 * Threat Hunting Workflow
 *
 * Fully autonomous threat hunting orchestration that:
 * 1. Agent analyzes Splunk structure and generates its own hunt plan
 * 2. Agent creates Splunk queries dynamically based on available data
 * 3. Agent executes queries and analyzes results for suspicious activities
 * 4. Deduplicates findings to prevent re-investigation
 * 5. Spawns investigations for new suspicious activities
 * 6. Generates new hunt plans each cycle - NOT limited by pre-defined patterns
 */

import { prisma } from '@/lib/db';
import { generateJudgeChallenge } from '../agents/judge-evaluator';
import { createAIClient } from '@/lib/ai';
import { createSplunkClientFromDB } from '@/lib/splunk/client';
import { loadAgentConfig } from '../agents/config-loader';
import { executeSplunkQueries } from '../agents/executor';
import { loadAllGuides } from '../agents/guide-loader';
import { executeAgenticWorkflow, generateAlertTitle } from '../agents/agentic-workflow';
import { getActiveWhitelistedIOCs } from '../agents/whitelist-helper';
import { executeAiPostHuntDeduplication } from './ai-deduplication';
import {
  generateFindingHash,
  filterDuplicates,
  isExistingFinding,
  type FindingData,
} from './deduplication';
import type {
  ThreatHuntConfig,
  ThreatHuntState,
  ThreatHunterOutput,
  ThreatFinding,
  ProcessedThreatFinding,
} from '../agents/types';

/**
 * Hunt objective generated by autonomous agent
 */
interface HuntObjective {
  id: string;
  name: string;
  description: string;
  whatToLookFor: string[];
  category: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
}

/**
 * Default configuration for threat hunting
 */
const DEFAULT_CONFIG: Required<ThreatHuntConfig> = {
  patterns: [], // Empty = use all patterns
  maxCycles: 10,
  cycleIntervalSeconds: 180, // 3 minutes
  maxFindingsPerPattern: 5,
  minSeverityForInvestigation: 'medium',
  deduplicationWindowHours: 24,
  autoCreateInvestigations: true,
  autoStartInvestigations: false, // Default to false - user starts manually
  aiProvider: 'glm', // Default to local model
  modelUsed: 'glm-4-plus',
  timeRange: {
    earliest: '-30d',
    latest: 'now',
  },
  focusAreas: [],
  cti: '',
};

/**
 * Severity order for comparison
 */
const SEVERITY_ORDER = ['low', 'medium', 'high', 'critical'];

/**
 * Check if severity meets threshold
 */
function meetsSeverityThreshold(
  severity: string,
  threshold: string
): boolean {
  const severityIndex = SEVERITY_ORDER.indexOf(severity.toLowerCase());
  const thresholdIndex = SEVERITY_ORDER.indexOf(threshold.toLowerCase());
  return severityIndex >= thresholdIndex;
}

/**
 * Start a new threat hunting session
 */
export async function startThreatHunt(
  config: Partial<ThreatHuntConfig> = {}
): Promise<string> {
  const mergedConfig = { ...DEFAULT_CONFIG, ...config };

  // Create threat hunt record
  const threatHunt = await prisma.threatHunt.create({
    data: {
      status: 'active',
      cyclesRun: 0,
      findingsCount: 0,
      config: mergedConfig as any,
    },
  });

  console.log(`[Threat Hunt] Started new threat hunt: ${threatHunt.id}`);

  // Start the workflow in the background
  executeThreatHuntWorkflow(threatHunt.id, mergedConfig).catch((error) => {
    console.error(`[Threat Hunt] Error in workflow: ${error.message}`);
    prisma.threatHunt.update({
      where: { id: threatHunt.id },
      data: {
        status: 'failed',
        errorMessage: error.message,
        completedAt: new Date(),
      },
    });
  });

  return threatHunt.id;
}

/**
 * Stop an active threat hunt
 */
export async function stopThreatHunt(threatHuntId: string): Promise<void> {
  await prisma.threatHunt.update({
    where: { id: threatHuntId },
    data: {
      status: 'completed',
      completedAt: new Date(),
    },
  });

  console.log(`[Threat Hunt] Stopped threat hunt: ${threatHuntId}`);
}

/**
 * Get threat hunt status
 */
export async function getThreatHuntStatus(
  threatHuntId: string
): Promise<ThreatHuntState | null> {
  const threatHunt = await prisma.threatHunt.findUnique({
    where: { id: threatHuntId },
    include: {
      findings: {
        orderBy: { detectedAt: 'desc' }, // FIXED: changed from createdAt to detectedAt to prevent crashes
        take: 100,
      },
    },
  });

  if (!threatHunt) {
    return null;
  }

  // Count findings by severity
  const criticalCount = threatHunt.findings.filter(
    (f) => f.severity === 'critical'
  ).length;
  const highCount = threatHunt.findings.filter(
    (f) => f.severity === 'high'
  ).length;
  const mediumCount = threatHunt.findings.filter(
    (f) => f.severity === 'medium'
  ).length;
  const lowCount = threatHunt.findings.filter((f) => f.severity === 'low').length;

  const investigationsSpawned = threatHunt.findings.filter(
    (f) => f.investigationId !== null
  ).length;

  const state: ThreatHuntState = {
    threatHuntId: threatHunt.id,
    status: threatHunt.status as any,
    currentCycle: threatHunt.cyclesRun,
    currentPatternId: undefined,
    config: threatHunt.config as ThreatHuntConfig,
    discoveredFindingHashes: new Set(threatHunt.findings.map((f) => f.findingHash)),
    stats: {
      totalFindings: threatHunt.findingsCount,
      criticalFindings: criticalCount,
      highFindings: highCount,
      mediumFindings: mediumCount,
      lowFindings: lowCount,
      investigationsSpawned,
      patternsProcessed: 0, // Would need to track separately
      cyclesCompleted: threatHunt.cyclesRun,
    },
    error: threatHunt.errorMessage || undefined,
    startedAt: threatHunt.startedAt,
    lastRunAt: threatHunt.lastRunAt || undefined,
    completedAt: threatHunt.completedAt || undefined,
  };

  return state;
}

/**
 * Generate autonomous hunt plan by having agent analyze Splunk structure
 */
async function generateHuntPlan(
  aiClient: any,
  cti?: string,
  agentConfig: any,
  splunkGuide: string,
  splunkStructure: string,
  investigatedTopics: Set<string>,
  cycle: number,
  timeRange: { earliest: string; latest: string },
  focusAreas?: string[],
  whitelistedIOCs?: any[]
): Promise<HuntObjective[]> {
  console.log(`[Threat Hunt] Asking agent to generate hunt plan (cycle ${cycle + 1})`);
  if (focusAreas && focusAreas.length > 0) {
    console.log(`[Threat Hunt] Focus areas: ${focusAreas.join(', ')}`);
  }

  // Format whitelisted IOCs for the prompt
  let whitelistSection = '';
  if (whitelistedIOCs && whitelistedIOCs.length > 0) {
    whitelistSection = `\n\n## WHITELISTED IOCs (IGNORE THESE)\n\nThe following IOCs are whitelisted and should be ignored in findings:\n\n`;
    const grouped = whitelistedIOCs.reduce((acc, ioc) => {
      if (!acc[ioc.type]) acc[ioc.type] = [];
      acc[ioc.type].push(`- ${ioc.value}${ioc.reason ? ` (${ioc.reason})` : ''}`);
      return acc;
    }, {} as Record<string, string[]>);

    for (const [type, values] of Object.entries(grouped) as [string, string[]][]) {
      whitelistSection += `**${type.toUpperCase()}:**\n${values.join('\n')}\n\n`;
    }
  }

  const planPrompt = `
# TASK: Generate Autonomous Threat Hunting Plan

You are a threat hunting agent tasked with creating a proactive hunt plan based on the available Splunk data.

## CONTEXT

**Hunt Cycle:** ${cycle + 1}
**Previously Investigated Topics:** ${investigatedTopics.size > 0 ? Array.from(investigatedTopics).join(', ') : 'None yet'}
**Time Range:** earliest=${timeRange.earliest}, latest=${timeRange.latest}
${focusAreas && focusAreas.length > 0 ? `**Focus Areas:** ${focusAreas.join(', ')} - Prioritize hunt objectives in these areas, but you may include others if relevant` : '**Focus Areas:** All areas - Hunt across all threat categories'}${whitelistSection}
${cti?`**Cyber Threat intelligence**: Keep a keen lookout on these known threats: ${cti}`:''}

## YOUR TASK

Analyze the "DISCOVERED INDEX STRUCTURE" section in your system prompt to understand what data is available in Splunk.

Based on the available data, generate 5-10 threat hunting objectives. Each objective should:
1. **Be unique** - Don't repeat topics that were already investigated
2. **Be specific** - Target a particular type of suspicious activity
3. **Be actionable** - Can be detected using available data
4. **Cover diverse threats** - Include different attack vectors (auth, network, endpoint, privilege escalation, data exfiltration, etc.)
5. **Leverage available data** - Only hunt for things detectable with the available indexes/sourcetypes
6. **Be on task** - If you were given a list of focus areas or threat intelligence, focus on those areas before moving to other areas

## CREATIVITY GUIDELINES

BE CREATIVE! Don't just look for the obvious. Consider:
- Unusual time patterns (activity at odd hours)
- Anomalous user behavior (users accessing unusual systems)
- Lateral movement indicators
- Persistence mechanisms
- Data staging and exfiltration
- Living-off-the-land techniques
- Cloud/SaaS abuse
- Supply chain indicators
- Insider threats

## OUTPUT FORMAT

Respond with JSON ONLY:

\`\`\`json
{
  "hunt_plan": [
    {
      "id": "unique-hunt-id-1",
      "name": "Short descriptive name",
      "description": "1-2 sentence description of what you're hunting for",
      "what_to_look_for": [
        "Specific indicator 1",
        "Specific indicator 2",
        "Specific indicator 3"
      ],
      "category": "authentication|endpoint|network|privilege|data_exfiltration|malware|cloud|other",
      "priority": "critical|high|medium|low"
    }
  ],
  "rationale": "Brief explanation of why you chose these hunt objectives based on available data"
}
\`\`\`

**IMPORTANT:** Only hunt for things you can actually detect with the available Splunk data. Review the DISCOVERED INDEX STRUCTURE first.

Generate your hunt plan now:
`.trim();

  try {
    const response = await aiClient.chat([
      {
        role: 'system',
        content: agentConfig.prompts.system + splunkGuide + splunkStructure,
      },
      {
        role: 'user',
        content: planPrompt,
      },
    ]);

    // Parse response
    const responseText = typeof response === 'string'
      ? response
      : response.content || response.message || String(response);

    const parsed = parseAgentOutput(responseText);

    if (!parsed || !parsed.hunt_plan || !Array.isArray(parsed.hunt_plan)) {
      console.error(`[Threat Hunt] Agent failed to generate valid hunt plan`);
      console.error(`[Threat Hunt] Response: ${responseText.substring(0, 500)}`);
      return [];
    }

    // Convert to HuntObjective format
    const objectives: HuntObjective[] = parsed.hunt_plan.map((obj: any) => ({
      id: obj.id,
      name: obj.name,
      description: obj.description,
      whatToLookFor: obj.what_to_look_for || [],
      category: obj.category || 'other',
      priority: obj.priority || 'medium',
    }));

    console.log(`[Threat Hunt] Agent rationale: ${parsed.rationale}`);

    return objectives;
  } catch (error: any) {
    console.error(`[Threat Hunt] Error generating hunt plan: ${error.message}`);
    return [];
  }
}

/**
 * Execute a single hunt objective - agent generates query, runs it, analyzes results
 */
async function executeHuntObjective(
  aiClient: any,
  agentConfig: any,
  objective: HuntObjective,
  splunkGuide: string,
  splunkStructure: string,
  maxFindings: number,
  timeRange: { earliest: string; latest: string },
  whitelistedIOCs?: any[],
): Promise<{ findings: ThreatFinding[]; query: string } | null> {
  console.log(`[Threat Hunt] Executing hunt objective: ${objective.name}`);

  // Step 1: Have agent generate Splunk query for this objective
  const queryPrompt = `
# TASK: Generate Splunk Query for Hunt Objective

## OBJECTIVE

**Name:** ${objective.name}
**Description:** ${objective.description}
**Priority:** ${objective.priority}

**What to Look For:**
${objective.whatToLookFor.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}

## TIME RANGE

**Earliest:** ${timeRange.earliest}
**Latest:** ${timeRange.latest}

## YOUR TASK

Review the "DISCOVERED INDEX STRUCTURE" in your system prompt and generate ONE optimized Splunk SPL query to hunt for this objective.


**Requirements:**
1. **MUST use ONLY** the indexes and sourcetypes from DISCOVERED INDEX STRUCTURE
2. **MUST use ONLY** the extracted field names listed in DISCOVERED INDEX STRUCTURE
3. **MUST include time range:** earliest=${timeRange.earliest} latest=${timeRange.latest}
4. **CRITICAL RULE FOR TIMESTAMPS:** Whenever you use a transforming command like \`| stats\` or \`| chart\`, you MUST preserve the timestamp by including \`earliest(_time) as first_seen, latest(_time) as last_seen\` in the aggregation. Example: \`| stats count, earliest(_time) as first_seen, latest(_time) as last_seen by src_ip\`. If you use \`| table\`, you MUST make \`_time\` the very first column.
5. Apply appropriate filters and aggregations
6. Follow Splunk best practices

**DO NOT** make assumptions about index/sourcetype/field names. Use only what's in the structure.

## OUTPUT FORMAT

Respond with ONLY the Splunk query. No explanations, no markdown code blocks. Just the pure SPL query.

Example:
index=windows sourcetype=WinEventLog:Security EventCode=4625 earliest=${timeRange.earliest} latest=${timeRange.latest} | stats count by src_ip, user | where count > 10 | sort - count

Generate query now:
`.trim();

  try {
    // Generate query
    const queryResponse = await aiClient.chat([
      {
        role: 'system',
        content: agentConfig.prompts.system + splunkGuide + splunkStructure,
      },
      {
        role: 'user',
        content: queryPrompt,
      },
    ]);

    const queryText = typeof queryResponse === 'string'
      ? queryResponse
      : queryResponse.content || queryResponse.message || String(queryResponse);

    const generatedQuery = extractQueryFromResponse(queryText);

    if (!generatedQuery) {
      console.log(`[Threat Hunt] Agent failed to generate query for ${objective.id}`);
      return null;
    }

    console.log(`[Threat Hunt] Generated query: ${generatedQuery.substring(0, 150)}...`);

// Step 2: Execute the query
    const tempAgentConfig = {
      ...agentConfig,
      splunk_queries: {
        common_queries: [
          {
            name: objective.id,
            spl: generatedQuery,
          },
        ],
      },
    };

    // FIX: Removed the fake timestamp so the Executor doesn't force a narrow 2-hour window.
    // This allows the Agent's SPL 'earliest' and 'latest' dates to actually take effect.
    const queryResultsMap = await executeSplunkQueries(tempAgentConfig, {
      investigationId: 'threat-hunt',
      alertData: { 
        is_threat_hunt: true,
        time_range: timeRange // Pass the broad config range as a fallback
      },
      // Dynamically pass the active provider instead of hardcoding openrouter
      aiProvider: aiClient?.providerName || aiClient?.provider || 'openrouter', 
    } as any);

    const queryResults = queryResultsMap[objective.id] || [];

    if (!queryResults || queryResults.length === 0) {
      console.log(`[Threat Hunt] No results from query for ${objective.id}`);
      return null;
    }

    console.log(`[Threat Hunt] Query returned ${queryResults.length} results`);

    // Step 3: Have agent analyze results for suspicious activities
    const formattedResults = formatResultsForAgent(queryResults);

    // Format whitelisted IOCs for the analysis prompt
    let whitelistSection = '';
    if (whitelistedIOCs && whitelistedIOCs.length > 0) {
      whitelistSection = `\n\n## WHITELISTED IOCs (DO NOT REPORT THESE)\n\nThe following IOCs are whitelisted and should NOT be included in findings:\n\n`;
      const grouped = whitelistedIOCs.reduce((acc, ioc) => {
        if (!acc[ioc.type]) acc[ioc.type] = [];
        acc[ioc.type].push(`- ${ioc.value}${ioc.reason ? ` (${ioc.reason})` : ''}`);
        return acc;
      }, {} as Record<string, string[]>);

      for (const [type, values] of Object.entries(grouped) as [string, string[]][]) {
        whitelistSection += `**${type.toUpperCase()}:**\n${values.join('\n')}\n\n`;
      }
      whitelistSection += `**IMPORTANT:** Filter out any findings that involve these whitelisted IOCs.\n`;
    }

    const analysisPrompt = `
# TASK: Analyze Results for Suspicious Activities

## HUNT OBJECTIVE

**Name:** ${objective.name}
**Description:** ${objective.description}
**Looking For:** ${objective.whatToLookFor.join('; ')}

## QUERY RESULTS

\`\`\`
${formattedResults}
\`\`\`${whitelistSection}

## YOUR TASK

Analyze the above results and identify any suspicious activities related to this hunt objective.

For each suspicious activity:
1. Extract title components: primary_entity (ONE most relevant user/host/IP) and key_detail (ONE critical indicator)
2. Extract affected entities (users, hosts, IPs, processes)
3. Assess severity (critical/high/medium/low) and confidence (0.0-1.0)
4. Provide 2-3 sentence description
5. Map to MITRE ATT&CK if applicable
6. **EXCLUDE** any activities involving whitelisted IOCs

## OUTPUT FORMAT

JSON ONLY:

\`\`\`json
{
  "findings": [
    {
      "title_detail": {
        "primary_entity": "192.168.1.50",
        "key_detail": "47 failed logins"
      },
      "finding_type": "${objective.id}",
      "description": "What was detected",
      "severity": "critical|high|medium|low",
      "confidence": 0.85,
      "affected_entities": {
        "users": [],
        "hosts": [],
        "ips": [],
        "processes": []
      },
      "mitre_attack": [],
      "raw_indicators": {}
    }
  ],
  "summary": {
    "total_findings": 1,
    "critical_count": 0,
    "high_count": 1,
    "medium_count": 0,
    "low_count": 0
  }
}
\`\`\`

If NO suspicious activities found, return empty findings array.

Analyze now:
`.trim();

    const analysisResponse = await aiClient.chat([
      {
        role: 'system',
        content: agentConfig.prompts.system,
      },
      {
        role: 'user',
        content: analysisPrompt,
      },
    ]);

    const analysisText = typeof analysisResponse === 'string'
      ? analysisResponse
      : analysisResponse.content || analysisResponse.message || String(analysisResponse);

    const output = parseAgentOutput(analysisText);

    if (!output || !output.findings) {
      console.log(`[Threat Hunt] No suspicious activities found for ${objective.id}`);
      return null;
    }

    const limitedFindings = output.findings.slice(0, maxFindings);
    console.log(`[Threat Hunt] Found ${limitedFindings.length} suspicious activities`);

    return {
      findings: limitedFindings,
      query: generatedQuery,
    };
  } catch (error: any) {
    console.error(`[Threat Hunt] Error executing objective ${objective.id}: ${error.message}`);
    return null;
  }
}

/**
 * Main threat hunting workflow
 */
export async function executeThreatHuntWorkflow(
  threatHuntId: string,
  config: Required<ThreatHuntConfig>
): Promise<void> {
  console.log(`[Threat Hunt] Starting workflow for hunt: ${threatHuntId}`);

  // Load threat hunter agent config
  const agentConfig = await loadAgentConfig('threat_hunter');
  if (!agentConfig) {
    throw new Error('Threat hunter agent configuration not found');
  }

  // Initialize AI client
  const aiClient = await createAIClient(config.aiProvider, {
    modelName: config.modelUsed,
  });

  // Load Splunk guide and structure (like investigation agents do)
  const splunkGuide = await loadAllGuides();
  const splunkStructure = await loadSplunkStructure();
  const whitelistedIOCs = await getActiveWhitelistedIOCs();

  console.log(`[Threat Hunt] Loaded Splunk guide (${splunkGuide.length} chars)`);
  console.log(`[Threat Hunt] Loaded Splunk structure (${splunkStructure.length} chars)`);
  console.log(`[Threat Hunt] Loaded ${whitelistedIOCs.length} whitelisted IOCs`);

  if (splunkStructure.length === 0) {
    console.warn(`[Threat Hunt] WARNING: No Splunk structure loaded! Agent may generate incorrect queries.`);
    console.warn(`[Threat Hunt] Please ensure Splunk config has fetched index structure.`);
  }

  // Track what has been investigated to avoid repeats
  const investigatedTopics = new Set<string>();

  // Determine time range for queries
  const timeRange = {
    earliest: config.timeRange?.earliest || '0', // Default to all time
    latest: config.timeRange?.latest || 'now',
  };

  console.log(`[Threat Hunt] Time range: earliest=${timeRange.earliest}, latest=${timeRange.latest}`);

  // Main autonomous hunting loop
  for (let cycle = 0; cycle < config.maxCycles; cycle++) {
    // Check if hunt was stopped
    const huntStatus = await prisma.threatHunt.findUnique({
      where: { id: threatHuntId },
      select: { status: true },
    });

    if (huntStatus?.status !== 'active') {
      console.log(`[Threat Hunt] Hunt ${threatHuntId} is no longer active, stopping`);
      break;
    }

    console.log(`[Threat Hunt] Cycle ${cycle + 1}/${config.maxCycles} - Generating autonomous hunt plan`);

    // Step 1: Have agent create a hunt plan based on Splunk structure
    const huntPlan = await generateHuntPlan(
      aiClient,
	config.cti,
      agentConfig,
      splunkGuide,
      splunkStructure,
      investigatedTopics,
      cycle,
      timeRange,
      config.focusAreas,
      whitelistedIOCs
    );

    if (!huntPlan || huntPlan.length === 0) {
      console.log(`[Threat Hunt] Agent couldn't generate hunt plan, ending hunt`);
      break;
    }

    console.log(`[Threat Hunt] Agent generated plan with ${huntPlan.length} hunt objectives`);

    let cycleFindings = 0;

    // Step 2: Execute each hunt objective in the plan
    for (const objective of huntPlan) {
      try {
        console.log(`[Threat Hunt] Executing: ${objective.name}`);

        // Agent generates query, executes it, and analyzes results
        const result = await executeHuntObjective(
          aiClient,
          agentConfig,
          objective,
          splunkGuide,
          splunkStructure,
          config.maxFindingsPerPattern,
          timeRange,
          whitelistedIOCs
        );

        // Mark this topic as investigated
        investigatedTopics.add(objective.id);

        if (!result || result.findings.length === 0) {
          console.log(`[Threat Hunt] No suspicious activities found for: ${objective.name}`);
          continue;
        }

        const { findings, query } = result;
        console.log(`[Threat Hunt] Agent identified ${findings.length} suspicious activities`);
        console.log(`[Threat Hunt] Query used: ${query.substring(0, 100)}...`);

        // Deduplicate findings
        const newFindings = await deduplicateAndProcessFindings(
          threatHuntId,
          objective.id,
          findings
        );

        if (newFindings.length === 0) {
          console.log(`[Threat Hunt] All findings were duplicates`);
          continue;
        }

        console.log(`[Threat Hunt] ${newFindings.length} new findings after deduplication`);

        // Save findings and spawn investigations
        for (const finding of newFindings) {
          await processFinding(threatHuntId, finding, config, query, objective);
          cycleFindings++;
        }
      } catch (error: any) {
        console.error(`[Threat Hunt] Error executing objective ${objective.name}: ${error.message}`);
        // Continue with next objective
      }
    }

    // Update hunt record
    await prisma.threatHunt.update({
      where: { id: threatHuntId },
      data: {
        cyclesRun: cycle + 1,
        lastRunAt: new Date(),
      },
    });

    console.log(`[Threat Hunt] Cycle ${cycle + 1} complete. Found ${cycleFindings} new findings.`);

    // Wait before next cycle (unless this is the last cycle)
    if (cycle < config.maxCycles - 1) {
      console.log(
        `[Threat Hunt] Waiting ${config.cycleIntervalSeconds} seconds before next cycle`
      );
      await sleep(config.cycleIntervalSeconds * 1000);
    }
  }
console.log(`[Threat Hunt] All cycles completed. Initiating AI post-hunt deduplication...`);
try {
  await executeAiPostHuntDeduplication(threatHuntId, config.aiProvider, config.modelUsed);
//*/* --- NEW: POST-HUNT JUDGE VERIFICATION ---
    /*console.log(`[Threat Hunt] Initiating Judge Verification Phase...`);
    const finalFindings = await prisma.threatFinding.findMany({
       where: { threatHuntId, status: 'pending' } // Only check findings that haven't been dismissed
    });

    for (const finding of finalFindings) {
       const challenge = await generateJudgeChallenge(
           config.aiProvider, 
           config.modelUsed, 
           'Threat Hunter', 
           finding.description
       );

       if (challenge) {
           console.log(`[Judge] Challenging finding ${finding.id}... forcing threat hunter to verify.`);
           // Call a targeted execution of the Threat Hunter specifically to run the Judge's challenge query
           const verificationResult = await runTargetedVerification(finding, challenge, config);
           
			if (verificationResult.error) {
               // 1. API crashed or token limit hit - DO NOT delete the finding!
               console.log(`[Judge] Verification skipped due to API error. Keeping finding ${finding.id} as pending. Reason: ${verificationResult.reason}`);
           } else if (!verificationResult.confirmed) {
               // 2. Safely executed, but no evidence was found. Reject it and append the reason.
               const rejectReason = verificationResult.reason || 'No raw log evidence found to substantiate the claim.';
               console.log(`[Judge] (ERROR!!!!!!) Hallucination detected. Reason: ${rejectReason}`);
               
               await prisma.threatFinding.update({
                   where: { id: finding.id },
                   data: { 
                       status: 'false_positive', 
                       description: finding.description + `\n\n[JUDGE_REJECTION]: ${rejectReason}` 
                   }
               });

               // If this finding is attached to a parent alert, resolve the parent alert too
               if (finding.alertId) {
                   await prisma.alert.update({
                       where: { id: finding.alertId },
                       data: { 
                           status: 'resolved', 
                           description: `Resolved by Judge Agent: False Positive\nReason: ${rejectReason}` 
                       }
                   });
               }
           } else {
               // 3. Evidence found!
               console.log(`[Judge] Finding ${finding.id} verified.`);
           }
       }
    }
    // -----------------------------------------*/
} catch (error) {
  console.error(`[Threat Hunt] AI Deduplication failed, but hunt will complete normally:`, error);
}
  // Mark hunt as completed
  await prisma.threatHunt.update({
    where: { id: threatHuntId },
    data: {
      status: 'completed',
      completedAt: new Date(),
    },
  });

  console.log(`[Threat Hunt] Hunt ${threatHuntId} completed successfully`);
  
}


/**
 * Format query results as a readable table for the agent
 */
function formatResultsForAgent(results: any[]): string {
  if (results.length === 0) {
    return 'No results returned from query.';
  }

  // Get all unique keys from results
  const allKeys = Array.from(
    new Set(results.flatMap((r) => Object.keys(r)))
  );

  // Create header row
  const header = allKeys.join(' | ');
  const separator = allKeys.map(() => '---').join(' | ');

  // Create data rows
  const rows = results.map((result) => {
    return allKeys.map((key) => result[key] || '').join(' | ');
  });

  return `${header}\n${separator}\n${rows.join('\n')}`;
}

/**
 * Parse agent output (JSON)
 */
function parseAgentOutput(response: string): ThreatHunterOutput | null {
  try {
    // Try to extract JSON from response (in case there's extra text)
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }

    // Try parsing directly
    return JSON.parse(response);
  } catch (error) {
    console.error(`[Threat Hunt] Failed to parse agent output: ${response.substring(0, 200)}`);
    return null;
  }
}

/**
 * Deduplicate findings and add metadata
 */
async function deduplicateAndProcessFindings(
  threatHuntId: string,
  patternId: string,
  findings: ThreatFinding[]
): Promise<ProcessedThreatFinding[]> {
  // Convert to FindingData format for deduplication
  const findingsData: FindingData[] = findings.map((f) => ({
    finding_type: f.finding_type,
    affected_entities: f.affected_entities,
    detected_at: new Date(),
    time_bucket_hours: 1,
  }));

  // Filter duplicates
  const newFindings = await filterDuplicates(findingsData, threatHuntId);

  // Combine with original finding data
  const processed: ProcessedThreatFinding[] = [];

  for (let i = 0; i < newFindings.length; i++) {
    const original = findings[i];
    const dedupData = newFindings.find(
      (nf) => nf.finding_type === original.finding_type
    );

    if (dedupData) {
      processed.push({
        ...original,
        hash: dedupData.hash,
        isDuplicate: false,
        patternId,
        detectedAt: new Date(),
      });
    }
  }

  return processed;
}

/**
 * Map finding type to query category
 */
function mapFindingTypeToCategory(findingType: string): string {
  const categoryMap: Record<string, string> = {
    'brute_force': 'authentication',
    'failed_login': 'authentication',
    'privilege_escalation': 'privilege_escalation',
    'suspicious_process': 'endpoint',
    'malware': 'malware',
    'lateral_movement': 'lateral_movement',
    'data_exfiltration': 'data_exfiltration',
    'network_anomaly': 'network',
	'prompt_injection':'malicious_prompting',
    'persistence': 'persistence',
    'defense_evasion': 'defense_evasion',
    'discovery': 'discovery',
  };

  // Try to find a match
  for (const [key, category] of Object.entries(categoryMap)) {
    if (findingType.toLowerCase().includes(key)) {
      return category;
    }
  }

  return 'other';
}

/**
 * Save or update query in the library
 * Returns the savedQueryId
 */
async function saveQueryToLibrary(
  splunkQuery: string,
  objective: HuntObjective,
  finding: ProcessedThreatFinding
): Promise<string> {
  // Check if query already exists (dedupe by SPL)
  const existingQuery = await prisma.savedQuery.findFirst({
    where: {
      splQuery: splunkQuery,
    },
  });

  if (existingQuery) {
    // Update existing query stats
    await prisma.savedQuery.update({
      where: { id: existingQuery.id },
      data: {
        findingsCount: { increment: 1 },
      },
    });
    console.log(`[Threat Hunt] Updated existing query in library: ${existingQuery.id}`);
    return existingQuery.id;
  }

  // Create new query
  const category = mapFindingTypeToCategory(finding.finding_type);
  const newQuery = await prisma.savedQuery.create({
    data: {
      name: objective.name,
      description: objective.description,
      splQuery: splunkQuery,
      category: category as any,
      severity: finding.severity,
      mitreAttack: finding.mitre_attack.length > 0 ? finding.mitre_attack[0] : null,
      isAutomated: true,
      findingsCount: 1,
    },
  });

  console.log(`[Threat Hunt] Saved new query to library: ${newQuery.id}`);
  return newQuery.id;
}

/**
 * Save finding and spawn investigation if needed
 */
async function processFinding(
  threatHuntId: string,
  finding: ProcessedThreatFinding,
  config: Required<ThreatHuntConfig>,
  splunkQuery: string,
  objective: HuntObjective
): Promise<void> {
  console.log(
    `[Threat Hunt] Processing finding: ${finding.finding_type} (${finding.severity})`
  );

  let alertId: string | undefined;
  let investigationId: string | undefined;
  let savedQueryId: string | undefined;

  // Save query to library (will dedupe if already exists)
  try {
    savedQueryId = await saveQueryToLibrary(splunkQuery, objective, finding);
  } catch (error) {
    console.error(`[Threat Hunt] Error saving query to library:`, error);
  }

  // Check for duplicates FIRST before creating alert/investigation
  const isDuplicate = await isExistingFinding(finding.hash, threatHuntId);
  
  if (isDuplicate) {
    console.log(`[Threat Hunt] Duplicate finding skipped: ${finding.hash.substring(0, 8)}...`);
    return; // Don't create alert/investigation for duplicates
  }

  // Always create alert for all findings (after deduplication)
  const alert = await prisma.alert.create({
    data: {
      source: 'Threat Hunt',
      severity: finding.severity,
      title: generateAlertTitle(
        finding.finding_type,
        finding.title_detail,
        finding.affected_entities
      ),
      description: finding.description,
      rawData: {
        finding: finding,
        pattern_id: finding.patternId,
        threat_hunt_id: threatHuntId,
        mitre_attack: finding.mitre_attack,
        time_range: {
          earliest: config.timeRange?.earliest || '0',
          latest: config.timeRange?.latest || 'now',
        },
        splunk_query: splunkQuery,
        hunt_objective: {
          id: objective.id,
          name: objective.name,
          description: objective.description,
        },
      } as any,
      status: 'new',
    },
  });

  alertId = alert.id;
  console.log(`[Threat Hunt] Created alert: ${alertId}`);

  // Determine if this finding should spawn an investigation
  const shouldInvestigate =
    config.autoCreateInvestigations &&
    meetsSeverityThreshold(finding.severity, config.minSeverityForInvestigation);

  if (shouldInvestigate) {
    console.log(`[Threat Hunt] Finding meets severity threshold, spawning investigation`);

    // Create investigation
    const investigation = await prisma.investigation.create({
      data: {
        alertId: alert.id,
        status: 'pending',
        priority: finding.severity === 'critical' ? 'critical' : finding.severity === 'high' ? 'high' : 'medium',
        aiProvider: config.aiProvider,
        modelUsed: config.modelUsed,
      },
    });

    investigationId = investigation.id;
    console.log(`[Threat Hunt] Created investigation: ${investigationId}`);

    // Update alert status based on whether investigation will auto-start
    await prisma.alert.update({
      where: { id: alert.id },
      data: { status: config.autoStartInvestigations ? 'investigating' : 'new' },
    });

    // Trigger investigation workflow only if auto-start is enabled
    if (config.autoStartInvestigations) {
      console.log(`[Threat Hunt] Auto-starting agentic workflow for investigation: ${investigationId}`);
	  await prisma.investigation.update({
        where: { id: investigationId },
        data: { 
          status: 'active',
		  startedAt: new Date()
        }
      });
      executeAgenticWorkflow(investigationId, alert, config.aiProvider || 'openrouter').catch((error) => {
        console.error(`[Threat Hunt] Error in agentic workflow for ${investigationId}:`, error);
      });
    } else {
      console.log(`[Threat Hunt] Investigation created but not auto-started (user can start manually): ${investigationId}`);
    }
  }

  // Save threat finding
  try {
    await prisma.threatFinding.create({
      data: {
        threatHuntId,
        findingHash: finding.hash,
        findingType: finding.finding_type,
        affectedEntities: finding.affected_entities as any,
        description: finding.description,
        severity: finding.severity,
        confidence: finding.confidence,
        rawData: finding.raw_indicators as any,
        mitreAttack: finding.mitre_attack.join(', '),
        alertId,
        investigationId,
        savedQueryId,
        status: 'pending',
      },
    });

    // Increment findings count
    await prisma.threatHunt.update({
      where: { id: threatHuntId },
      data: {
        findingsCount: { increment: 1 },
      },
    });

    console.log(`[Threat Hunt] Finding saved to database`);
  } catch (error: any) {
    // Handle race condition: another process created the finding between our check and now
    if (error.code === 'P2002') {
      console.log(`[Threat Hunt] Duplicate finding skipped (race condition): ${finding.hash.substring(0, 8)}...`);
      
      // Clean up orphaned alert/investigation if created
      if (alertId) {
        console.log(`[Threat Hunt] Cleaning up orphaned alert: ${alertId}`);
        await prisma.alert.delete({ where: { id: alertId } }).catch(() => {});
      }
      if (investigationId) {
        console.log(`[Threat Hunt] Cleaning up orphaned investigation: ${investigationId}`);
        await prisma.investigation.delete({ where: { id: investigationId } }).catch(() => {});
      }
    } else {
      throw error;
    }
  }
}

/**
 * Load Splunk index structure from database
 */
async function loadSplunkStructure(): Promise<string> {
  try {
    const splunkConfig = await prisma.splunkConfig.findFirst({
      where: { isActive: true },
      select: { indexStructure: true, structureFetchedAt: true },
    });

    if (!splunkConfig?.indexStructure || !splunkConfig.structureFetchedAt) {
      return '';
    }

    const structure = splunkConfig.indexStructure as Record<string, Record<string, { fields: string[] }>>;

    let structureText = `\n\n=== DISCOVERED INDEX STRUCTURE (Fetched: ${new Date(splunkConfig.structureFetchedAt).toLocaleString()}) ===\n\n`;
    structureText += `This section contains actual indexes, sourcetypes, and EXTRACTED FIELDS from your Splunk instance.\n`;
    structureText += `IMPORTANT: These fields are PRE-EXTRACTED by Splunk and available for immediate use in queries.\n`;
    structureText += `DO NOT use rex or regex commands to extract these fields - they are already available!\n\n`;

    for (const [index, sourcetypes] of Object.entries(structure)) {
      structureText += `\nIndex: ${index}\n`;
      structureText += `${'='.repeat(50)}\n`;

      for (const [sourcetype, data] of Object.entries(sourcetypes)) {
        structureText += `\n  Sourcetype: ${sourcetype}\n`;
        structureText += `  ${'-'.repeat(48)}\n`;

        if (data.fields && data.fields.length > 0) {
          structureText += `  Extracted Fields (${data.fields.length}):\n`;
          structureText += `  ${data.fields.join(', ')}\n`;
        } else {
          structureText += `  Extracted Fields: None found\n`;
        }
      }
    }

    structureText += `\n${'='.repeat(50)}\n`;
    structureText += `CRITICAL: The fields listed above are ALREADY EXTRACTED. Use them directly in your queries.\n`;
    structureText += `Example: index=vpcflow srcaddr="10.0.0.1" (NOT: index=vpcflow | rex "..." )\n`;

    return structureText;
  } catch (error) {
    console.error('[Threat Hunt] Error loading Splunk structure:', error);
    return '';
  }
}

/**
 * Extract Splunk query from agent response
 */
function extractQueryFromResponse(response: string): string | null {
  // Try to find query in code blocks first using RegExp to prevent UI parser breaks
  const codeBlockRegex = new RegExp('\\x60{3}(?:spl|splunk)?\\n?([\\s\\S]+?)\\n?\\x60{3}');
  const codeBlockMatch = response.match(codeBlockRegex);
  
  if (codeBlockMatch) {
    return codeBlockMatch[1].trim();
  }

  // Try to find lines that look like SPL
  const lines = response.split('\n');
  const queryLines: string[] = [];
  let inQuery = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Start of query (contains index= or search command)
    if (!inQuery && (trimmed.startsWith('index=') || trimmed.startsWith('search ') || trimmed.startsWith('| '))) {
      inQuery = true;
      queryLines.push(trimmed);
      continue;
    }

    // Continuation of query (starts with |)
    if (inQuery && trimmed.startsWith('|')) {
      queryLines.push(trimmed);
      continue;
    }

    // End of query
    if (inQuery && trimmed && !trimmed.startsWith('|') && !trimmed.startsWith('index=')) {
      break;
    }
 
    if (inQuery && trimmed) {
      queryLines.push(trimmed);
    }
  }

  if (queryLines.length > 0) {
    return queryLines.join('\n');
  }

  // Last resort: return the whole response if it looks like a query
  if (response.includes('index=') || response.includes('| stats') || response.includes('| search')) {
    return response.trim();
  }

  return null;
}

/**
 * Utility: Sleep function
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Executes a targeted verification hunt to prove or disprove a finding based on the Judge's challenge.
*/
async function runTargetedVerification(
  finding: any,
  challenge: string,
  config: any
): Promise<{ confirmed: boolean; error?:boolean; reason?:string }> {
  console.log(`[Threat Hunt] Running targeted verification for finding ${finding.id}...`);
  
  try {
    const agentConfig = await loadAgentConfig('threat_hunter');
    if (!agentConfig) return { confirmed: false };

    const aiClient = await createAIClient(config.aiProvider, { modelName: config.modelUsed });
    const splunkGuide = await loadAllGuides();
    const splunkStructure = await loadSplunkStructure();
    const timeRange = {
      earliest: config.timeRange?.earliest || '0',
      latest: config.timeRange?.latest || 'now',
    };

    // 👇 FETCH SPLUNK STRUCTURE FOR THE PROMPT 👇
    let discoveredStructure = '';
    try {
      const splunkConfig = await prisma.splunkConfig.findFirst({
        where: { isActive: true },
        select: { indexStructure: true },
      });

      if (splunkConfig?.indexStructure) {
        discoveredStructure = `\n=== AVAILABLE SPLUNK INDEXES & FIELDS ===\n${JSON.stringify(splunkConfig.indexStructure)}\n`;
      }
    } catch (dbError) {
      console.error('[Threat Hunt] Could not load index structure for verification');
    }
    // 👆 --------------------------------------- 👆

    // Create a temporary objective strictly based on the Judge's challenge
    const objective: HuntObjective = {
      id: `verify-${finding.id}`,
      name: `Verification: ${finding.findingType || 'Suspicious Activity'}`,
      description: `JUDGE DIRECTIVE: ${challenge}`,
      whatToLookFor: [challenge],
      category: 'verification',
      priority: 'high'
    };

    const systemPrompt = `
    You are an expert Splunk threat hunter. 
    Your objective is to run a targeted Splunk query to verify this specific claim:
    
    CLAIM TO VERIFY:
    ${challenge}
    
    ${discoveredStructure}
    
    IMPORTANT RULES FOR VERIFICATION QUERIES:
    1. Output ONLY the raw Splunk SPL query. Do not use markdown, do not use JSON.
    2. Write BROAD, simple queries to pull the raw logs. Avoid complex 'stats', 'eval', or 'where' clauses on your first attempt.
    3. Use simple wildcard searches (e.g., *bedrock* OR *nova*) rather than strict field matching if you are unsure of the exact field names.
    4. Always include earliest= and latest= bounds based on the timeframes mentioned in the claim.
    `;

    const result = await executeHuntObjective(
      aiClient,
      agentConfig,
      objective,
      splunkGuide,
      splunkStructure,
      1, // We only need 1 hard piece of evidence to confirm it
      timeRange,
      []
    );

    // If the agent was able to successfully query and return a finding based on the strict challenge, it is confirmed!
    if (result && result.findings && result.findings.length > 0) {
      return { confirmed: true };
    }

    return { 
      confirmed: false, 
      reason: "The targeted verification query returned 0 results in Splunk. The claimed logs could not be found." 
    };
  } catch (error: any) {
    console.error(`[Threat Hunt] Verification failed to execute:`, error);
    return { 
      confirmed: false, 
      error: true, 
      reason: `API or execution error: ${error.message}` 
    }; 
  }
}
